<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter new password</name>
   <tag></tag>
   <elementGuidId>82197ca1-8e8d-4223-821f-4863d0a8a962</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#new_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'new_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d122f637-4f13-41a5-b02c-3cd18a832183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>acct-field__input</value>
      <webElementGuid>06218f00-0943-4624-b5fd-235d6e99eaa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>cc054c3f-b4d4-4ee2-935a-c0dccf14b8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>new_password</value>
      <webElementGuid>32bd8b46-24b2-4afa-87f4-96cca1970cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>new_password</value>
      <webElementGuid>dac3d051-9871-4a1b-94d7-4ee640e60323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter new password</value>
      <webElementGuid>7d39aaba-bc1c-4a2b-ae9d-e198b8fefb0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>88e206a3-40c0-47b6-ad15-b2b485891cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>pw-new-password-hint</value>
      <webElementGuid>15b1497d-7a8f-48f7-ab65-0f8b861934eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-19a2a0353a8c5706584e0af382db5c7a</value>
      <webElementGuid>a99580b6-a7b6-43d8-a58c-29e742a599cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'new_password']</value>
      <webElementGuid>c4f4e59a-55f6-495b-bd6b-4bc7d00d29a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'new_password']</value>
      <webElementGuid>efe13ed7-2598-402e-af0c-b596ec4a63f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'new_password' and @name = 'new_password' and @placeholder = 'Enter new password']</value>
      <webElementGuid>d2fcf237-cdbe-4ff2-be2b-094032d5c2ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
