<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username</name>
   <tag></tag>
   <elementGuidId>c55883bb-56cb-4a67-94ce-ac63ae25bae8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtUserName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'txtUserName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>892c67c9-b683-4ef4-a56c-2b8b604f3020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d5b0f0dd-8c43-4fbe-9aa9-7b5b721c3db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtUserName</value>
      <webElementGuid>afbd0645-9c36-4ab0-b659-b2d7e2c10133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtUserName</value>
      <webElementGuid>2f311062-665a-4248-afe4-d43404289dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-form__input</value>
      <webElementGuid>4bc384eb-51f3-4fe6-9fb3-23a5f3cdc103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>b9e7947e-f53c-4e20-845c-2ad9cef9a0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>190b4278-8ab8-47c5-9c45-02a867b50326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f7b10e56-2db2-4496-9a97-d83b6d1a9ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>61a6b972-226e-4fab-a4d7-f325977d4141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-905015e9c4ede2d3d947276ec855bcf7</value>
      <webElementGuid>dbfaf631-b2e0-456f-a12c-a21610a9689e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'txtUserName']</value>
      <webElementGuid>e2c4cd79-3340-4092-bde9-b2ba50be00ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'txtUserName']</value>
      <webElementGuid>d3ab35f9-7c0a-436d-9a3a-bc1cefda6b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txtUserName' and @id = 'txtUserName' and @placeholder = 'Username']</value>
      <webElementGuid>eb152e73-264b-48e4-b1c2-49ea69f2fe22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
