<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your email</name>
   <tag></tag>
   <elementGuidId>2998fdb4-1035-495a-831f-89c1a253ba77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#forgotEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'forgotEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79402d6d-a717-4891-bb4a-beded9dc37cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>eab44dc7-264f-48da-88cf-69ea25901226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>forgotEmail</value>
      <webElementGuid>a37b6afc-7c7a-4f27-97d4-d926fdeab24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-form__input</value>
      <webElementGuid>134a9f83-1061-49bd-8d8d-16611d6f0597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email</value>
      <webElementGuid>0d8aa345-9df7-485c-a53d-d8f9b9cd0c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d467920625d87ef9ba0b6051cedfd47c</value>
      <webElementGuid>3fb5c9ad-0464-40ee-b49f-6767a50eb16b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'forgotEmail']</value>
      <webElementGuid>2e72b305-599a-442f-916a-00fd3e76b8e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'forgotEmail']</value>
      <webElementGuid>330bb2f0-91b6-4944-bc0a-603919dbfe8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'forgotEmail' and @placeholder = 'Enter your email']</value>
      <webElementGuid>39093be9-f59e-417b-855d-8bceb9d583ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
