<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your current password</name>
   <tag></tag>
   <elementGuidId>f7cf6946-9ed8-4e1a-b8df-b41d0fa6aff0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#current_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'current_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7f577ce-6a7f-4e30-bae3-16ff448ce7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>acct-field__input</value>
      <webElementGuid>ac670b23-b63a-4e71-9be8-399c6ac05a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>944c8242-7c36-43ee-9282-36615e44403c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>current_password</value>
      <webElementGuid>04369c6c-8927-4b2e-b4a4-988cfc4c9429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>current_password</value>
      <webElementGuid>e2f8b561-3433-491e-9048-ec9dfa93f1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your current password</value>
      <webElementGuid>11868e4f-c77e-4010-b8df-5b2a202a3f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>d2c7a233-9526-4086-bd5c-e18d9198ce07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b08a7470e03381f9df7e099ce2a4baf3</value>
      <webElementGuid>9cc77d82-41b2-4f26-a487-f2b5b0bb9a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'current_password']</value>
      <webElementGuid>d25e6777-f0a9-465d-9eb6-26741b985a65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'current_password']</value>
      <webElementGuid>fdb837cd-4dba-48ac-9ad7-abcb61b0df1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'current_password' and @name = 'current_password' and @placeholder = 'Enter your current password']</value>
      <webElementGuid>b4ac2190-2eeb-4239-a2ee-2e4a741ec87f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
