<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm new password</name>
   <tag></tag>
   <elementGuidId>4c03cb7f-fbc1-41ca-ba2c-d34a19def03b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirm_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'confirm_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26e33969-e7dd-4c60-aa1f-1d2c47547339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>acct-field__input</value>
      <webElementGuid>62606bf2-ae7b-46ef-aa67-4020f66df2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c7675c48-f57d-42b5-8e72-35220094a371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirm_password</value>
      <webElementGuid>63cec6cb-6889-4c67-8e43-77f8575f196b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm_password</value>
      <webElementGuid>ad5451e8-57e9-462b-91c5-2c6ece83eca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm new password</value>
      <webElementGuid>cc2acb3d-9294-4565-a64f-a41b559c22a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>db893059-aa9a-4b23-bbd2-9c2cb538840f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-27350a7be9fca6561f76e3e6e7f8b785</value>
      <webElementGuid>69bbb32e-bf39-4420-9297-01ceae49cde3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'confirm_password']</value>
      <webElementGuid>0c9f6d8d-7cd3-4273-94cc-5c8a81315e5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'confirm_password']</value>
      <webElementGuid>2b1156b1-ae5b-4562-8c27-e76e0aceccc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'confirm_password' and @name = 'confirm_password' and @placeholder = 'Confirm new password']</value>
      <webElementGuid>e5303476-265f-4247-971b-a7c3ef1df24e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
