<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Vouchers</name>
   <tag></tag>
   <elementGuidId>ae330cd2-0fb7-47f6-b0bc-b900db0aeb31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.vouchers__title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' vouchers__title ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>e9c208f8-8a89-4c59-b9bb-3e8c51f69aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vouchers__title</value>
      <webElementGuid>3f97c3fe-23de-4668-bc40-2b5cf0f0d55c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vouchers</value>
      <webElementGuid>346e5526-9e63-4f1f-97ba-bc4d2616b0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ff21e01de54ebaa4bde604d014a42512</value>
      <webElementGuid>7d134f19-e925-4675-a13c-a772ed370345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' vouchers__title ')]</value>
      <webElementGuid>493ca0af-17de-451b-9904-7f976a4d003d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' vouchers__title ')]</value>
      <webElementGuid>b8e43074-3d25-42b1-ba1f-d216a8f55295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Vouchers' or . = 'Vouchers')]</value>
      <webElementGuid>9f99241b-a4bc-46fd-906c-936a6c29bbf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
