<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Reports</name>
   <tag></tag>
   <elementGuidId>10fa5f5d-f3b2-441c-b841-27f755a53c63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@name='frmReports']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.reports-one-header__title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>c31dfca8-c7a6-435c-abf3-f89895305d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reports-one-header__title</value>
      <webElementGuid>9d962f36-3e77-47c1-a97a-d0a5312c2213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reports</value>
      <webElementGuid>18df9c04-a86e-491e-ab78-40eceac8ac41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8c8f1be37b1604aabfa79d7a45340646</value>
      <webElementGuid>10ea20f3-05b0-4474-a719-07b9246b469d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' reports-one-header__title ')]</value>
      <webElementGuid>629baec1-9619-4c81-9019-d8e5f85868c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' reports-one-header__title ')]</value>
      <webElementGuid>5d7543e3-a36c-4945-a720-72c14d0c8d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Reports' or . = 'Reports')]</value>
      <webElementGuid>82c0207b-4883-4d65-88ad-e8bb04178156</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
