<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_tab-insights</name>
   <tag></tag>
   <elementGuidId>00a77449-561c-4576-a1e6-056277dee1d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-insights</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'tab-insights']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52adde47-83b0-4d3d-8e1e-e9c4fe9e9857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ecosystem__tab</value>
      <webElementGuid>696a7775-de19-45bd-8949-c6806c69077d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>537fc905-10e3-4fc1-8d39-db8577ae886c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>55d2b283-8292-4033-97aa-538846c7bd78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>panel-insights</value>
      <webElementGuid>35f7173b-69d1-45cb-9af2-0619453c3499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-insights</value>
      <webElementGuid>c7a293a4-d51a-4a7a-aa1b-f1848ab9ec01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8f3ada2d-0756-45ba-8787-a8c4ecdd431e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          FTG Insights
        </value>
      <webElementGuid>7acef887-3ab6-4643-b32a-58de9aa0550f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d030579906e682f7d7bac8085fc246bd</value>
      <webElementGuid>b3ea0fc2-9531-403d-b974-dde22fd5cc51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'tab-insights']</value>
      <webElementGuid>515d844a-502f-47f0-8d29-b01c7b79d038</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'tab-insights']</value>
      <webElementGuid>bdb63c10-ff0e-440a-a358-8b969f117378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'tab-insights' and (text() = '
          FTG Insights
        ' or . = '
          FTG Insights
        ')]</value>
      <webElementGuid>025c3f38-aabf-4a59-894f-0f9ecde4efbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
