<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username</name>
   <tag></tag>
   <elementGuidId>8b96d931-6c02-4f38-ad59-86170c845e9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtUserName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'txtUserName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b3aabb3-533c-4e55-baf4-4cace5b992ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>df8c5bd1-ffbd-4bb7-a67c-9cac1844adad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtUserName</value>
      <webElementGuid>65d41e1f-3d31-4c31-8411-0988ea11d7eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtUserName</value>
      <webElementGuid>8bb3d49f-da6d-46d3-963c-92db68cf09c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-form__input</value>
      <webElementGuid>bc4c0f26-4b98-4b40-83e6-77e9d4c9eba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>f7c9681e-395d-4c8f-89a5-468328bbfadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>82efd961-5567-4e23-9b1e-43b97aa9386c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ee82d79c-9432-47dc-8cab-4ae4bb250334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>08012984-c2ac-438e-afb2-a6ef90abb780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-905015e9c4ede2d3d947276ec855bcf7</value>
      <webElementGuid>ef4ec4da-eb7d-4fb2-b13d-a0794df1d8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'txtUserName']</value>
      <webElementGuid>ee81f68c-4696-4221-b0fd-58d9ae34d498</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'txtUserName']</value>
      <webElementGuid>634468f7-0bd2-4c2f-bc9e-d79b75be37e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txtUserName' and @id = 'txtUserName' and @placeholder = 'Username']</value>
      <webElementGuid>d413f1c9-d424-452d-b352-b711f7a39ea7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
