<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_sendAmount</name>
   <tag></tag>
   <elementGuidId>39e1c488-2301-4a82-9cb1-d5861ad45be7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#send-amount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'send-amount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d90d340-921b-4e4b-ada6-f3cc9418542b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>send-tokens__amount-input</value>
      <webElementGuid>d5bbe6a9-4eb9-4d4a-9afe-22be6389f7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>send-amount</value>
      <webElementGuid>61e937c7-f7f6-4c36-bcef-915c357860ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>send_amount</value>
      <webElementGuid>9cebf671-8dee-423a-9af8-047489a2966f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b2d7c088-168c-49f5-9353-f0fecc68980b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>8a36de2a-46ac-416a-9ad3-86159163611d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>8c142d34-bb54-441e-ab94-17ae82db097f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>116a9543-4b61-45d4-83db-9bddb91b1c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9b93197d-526d-4c38-a019-25aca425fa6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>FTG tokens to send per recipient</value>
      <webElementGuid>a71dfdf1-9a72-4bbe-9c6c-d116c6bb26df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>send-amount-error</value>
      <webElementGuid>5af6cd13-34af-454b-bde1-4e097328a21a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8fb4352c-6e70-4e40-a51a-ddb396eb23f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>28e34f86-8cc8-4d20-9e89-a07502860b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-845bd841cc294b0e6ab9c692e8c1e25d</value>
      <webElementGuid>6bf3022a-b616-4f5d-b9b6-0e350dc75074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'send-amount']</value>
      <webElementGuid>31dc0fb2-9f2b-47a7-b68c-5bd8239387fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'send-amount']</value>
      <webElementGuid>9b3492df-7673-47fe-978e-09fae289ebf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'send-amount' and @name = 'send_amount' and @type = 'text' and @placeholder = '0.00']</value>
      <webElementGuid>4352cc27-7936-40a7-ab98-3c3e419c22bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
