<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_recieverName</name>
   <tag></tag>
   <elementGuidId>3cd68ebf-6ed9-4487-8a8d-0f16ecd5d541</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#send-to</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'send-to']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>341eaa9c-79f8-49c5-9608-75fa19ad52c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>send-tokens__input send-tokens__input--search</value>
      <webElementGuid>996a6efd-fac3-4908-895d-7affa933637c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>18c3b6de-4dec-47f3-9304-8197395d11c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>send-to</value>
      <webElementGuid>8b8473aa-6ebb-4a3a-bfc6-b499365c78f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by name, email, or ID</value>
      <webElementGuid>49cfa46b-2489-4a13-b7be-8cac9126fd28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5e3bd979-37f2-4280-ad62-0635adec2c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search recipient by name, email, or ID</value>
      <webElementGuid>e7d6dd37-22f5-49ba-9d2e-1f8695d90f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>send-to-note send-to-error</value>
      <webElementGuid>c8b97ed8-2526-4fa7-b59d-7809ad5cfc9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7b969f64-7776-4ebf-bcf8-90e4d296c7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>search-results</value>
      <webElementGuid>ab3d928a-ea63-4b93-bf01-627b845d1ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>af5ebb5d-80d8-443c-88f8-6df590308022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7c09b52501e8a5e1c6d15c4484e9a81c</value>
      <webElementGuid>6716ace4-1dea-4af0-ae6e-2019abc73b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'send-to']</value>
      <webElementGuid>486cc193-17a9-4699-bb6f-f1f6be618393</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'send-to']</value>
      <webElementGuid>c5cc0b57-1fe3-4fe2-a1e5-9998bd7b2922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'send-to' and @placeholder = 'Search by name, email, or ID']</value>
      <webElementGuid>b81f7314-137e-4142-9859-f95da5f7ec25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
