<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_description</name>
   <tag></tag>
   <elementGuidId>1bb161d9-e546-49d9-b4d2-08956b7ec35b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#send-details</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'send-details']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b1f51886-4f31-4a2e-8922-50f1f42ac313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>send-tokens__textarea</value>
      <webElementGuid>d8d41610-233f-4046-8257-4c8e9a1ac699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>send-details</value>
      <webElementGuid>32d2db47-8aff-4462-bd79-06302f4c2a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reason</value>
      <webElementGuid>cade6e1b-2622-460d-a75f-db04e8184b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter details</value>
      <webElementGuid>badb8333-87be-472e-9ed5-13a66a10c1d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>2802af6e-fa77-445e-8348-d147a206f4aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dcde492d-29ab-47b9-8905-3a8788930b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>send-details-error send-details-count</value>
      <webElementGuid>3b45cbd7-7587-4ab8-8d85-9ad261318363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8d9fe95a-7f85-4d28-9cd4-599c0ba7ea07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-33f5f96bad380e4221ec5a7962df73ce</value>
      <webElementGuid>9dd01f7c-be35-41e6-ad1b-0da4ecec1d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'send-details']</value>
      <webElementGuid>20b60c27-1039-4013-b7d0-9af6940cb2f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'send-details']</value>
      <webElementGuid>b9d85aa8-9df4-4dc9-9c2e-dd42eaa3910f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'send-details' and @name = 'reason' and @placeholder = 'Enter details']</value>
      <webElementGuid>977b10ee-8307-4e70-8ce8-ebf8e2586153</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
