<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_login_rememberMe</name>
   <tag></tag>
   <elementGuidId>3f3bf4e9-9a4c-4bde-afaf-05f20fd91a83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.login-form__checkbox-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>id(&quot;frmLogin&quot;)/div[@class=&quot;login-form__checkbox-group&quot;]/label[@class=&quot;login-form__checkbox-label&quot;]/span[@class=&quot;login-form__checkbox-box&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>27024115-5c53-4554-be87-dd12d133c3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-form__checkbox-box</value>
      <webElementGuid>20861196-d9e3-466e-a393-fec972076fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a8c8f378-4033-4325-b5f9-d513f16b9cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmLogin&quot;)/div[@class=&quot;login-form__checkbox-group&quot;]/label[@class=&quot;login-form__checkbox-label&quot;]/span[@class=&quot;login-form__checkbox-box&quot;]</value>
      <webElementGuid>c74d749b-3bb4-4b0b-86b2-7eea8014fd1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmLogin']/div[3]/label/span</value>
      <webElementGuid>f0f3bbe4-b01e-44a0-816d-4d1048b7c192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::span[1]</value>
      <webElementGuid>1343aa2d-7b7d-473f-9450-cf7c475b3f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::span[1]</value>
      <webElementGuid>9e6be18a-402a-4c03-8529-3c0adfe8515d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>ef1fb6c8-e274-4c1b-92f8-de30f270fb5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
