<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>element_dashboard_exist</name>
   <tag></tag>
   <elementGuidId>46d12bd1-b6cd-4eaa-a43b-b902fcb2492e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = 'Verified Energy Network']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>89f137b9-b041-49ce-a69e-82b26ce2edc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d272pp5vvcmeut.cloudfront.net/gizlayouts/asset/img/FaradConnect.svg</value>
      <webElementGuid>054cbd28-091a-491c-88fc-0ca9dd05e5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/nav[@class=&quot;navbar navbar-expand-sm navbar-dark bg-white main-nav main-top-pad top-nav-position fixed-top&quot;]/div[@class=&quot;container-fluid&quot;]/a[@class=&quot;navbar-brand logo-lt logo-top&quot;]/img[1]</value>
      <webElementGuid>87cb2572-e0fb-4def-ab12-ac28bd19607a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://d272pp5vvcmeut.cloudfront.net/gizlayouts/asset/img/FaradConnect.svg')]</value>
      <webElementGuid>69f81587-8e6b-467c-a290-9d7d8fe2d6c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>1be9d204-0ea3-4305-849b-1fd0c775ddaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d272pp5vvcmeut.cloudfront.net/gizlayouts/asset/img/FaradConnect.svg']</value>
      <webElementGuid>16d72ec3-e867-4828-ab64-6ac38f383cb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
