<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>element_dashboard_exist</name>
   <tag></tag>
   <elementGuidId>46d12bd1-b6cd-4eaa-a43b-b902fcb2492e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://d272pp5vvcmeut.cloudfront.net/gizlayouts/asset/img/FaradConnect.svg')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a57719a4-6888-4a1a-84ab-88cc8701f718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d272pp5vvcmeut.cloudfront.net/gizlayouts/asset/img/FaradConnect.svg</value>
      <webElementGuid>c206004a-4591-4edf-bde5-61327d297c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/nav[@class=&quot;navbar navbar-expand-sm navbar-dark bg-white main-nav main-top-pad top-nav-position fixed-top&quot;]/div[@class=&quot;container-fluid&quot;]/a[@class=&quot;navbar-brand logo-lt logo-top&quot;]/img[1]</value>
      <webElementGuid>1088674f-bafe-4c52-81c0-2f98c2b3edcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://d272pp5vvcmeut.cloudfront.net/gizlayouts/asset/img/FaradConnect.svg')]</value>
      <webElementGuid>d18d9b3e-1ae4-483b-ad8f-853baa0507cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>725e348d-f9da-42dd-bd09-a323dceadeea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d272pp5vvcmeut.cloudfront.net/gizlayouts/asset/img/FaradConnect.svg']</value>
      <webElementGuid>2bee90ad-31e3-4545-9252-737068a2f93c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
