<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_vmodal-verify</name>
   <tag></tag>
   <elementGuidId>269000d5-61e4-4517-95e3-6fa17dd17198</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'vmodal-verify']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vmodal-verify</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e329844-0e90-4796-8159-33ed457e3537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vmodal__verify-btn is-ready</value>
      <webElementGuid>937b2fda-691f-4fbd-b8b5-105720f0977d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vmodal-verify</value>
      <webElementGuid>dee0b3a1-9960-432a-820f-51ef9e48ca29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8bbcf143-2e23-44c8-9929-09cf0d45aa73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2e36ff55-2cd2-41ac-9789-640d3952cb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify</value>
      <webElementGuid>3c1fc52b-2c23-4f8c-8586-3d802414bfef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4a1bdbe775ebf9a85ab9075ae9478408</value>
      <webElementGuid>45e5e628-d61f-470e-a7a0-4d642dd7b2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'vmodal-verify']</value>
      <webElementGuid>8d48d96a-7734-4a56-bc0d-1b3562da5279</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'vmodal-verify']</value>
      <webElementGuid>6b1dcdf3-af30-45e1-9efb-9f5d432298ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'vmodal-verify' and @type = 'button' and (text() = 'Verify' or . = 'Verify')]</value>
      <webElementGuid>ee3cecd7-459b-4206-a797-fef9429cccb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
