<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Re-enter routing number</name>
   <tag></tag>
   <elementGuidId>a661a517-6a21-4715-bdb5-7f0b3401b1e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'ach-routing-confirm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ach-routing-confirm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86d79351-16de-41ee-842e-3542af5f845b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d8343f8f-e82f-444e-be6e-e16182d75b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ach-routing-confirm</value>
      <webElementGuid>e5b50271-93aa-41b9-9720-dfc7012ca012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ach_routing_confirm</value>
      <webElementGuid>e2821337-5a5b-433d-bb57-c8c52bfeca83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>withdraw-ach-field__input withdraw-ach-field__input--emphasis</value>
      <webElementGuid>8fd2282e-2b02-4382-9050-90c408b8f166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>78cc5673-dafe-4bed-8dcd-14c0ff6f071a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>f0c67a25-c8fa-4b6e-a0cd-18cb96f8b953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6c842376-21eb-4a9d-b0b7-dce3536165bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Re-enter routing number</value>
      <webElementGuid>fd555c88-6774-41b0-907b-5c59b32dc4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e33755cb-c4e1-4a6a-beae-9c6a256f662d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e5fccf3a4ba40b3ae7b69b0eab135b07</value>
      <webElementGuid>2a4bc717-4ae6-4115-b73e-12cf06d1cfb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'ach-routing-confirm']</value>
      <webElementGuid>129a2132-8d90-4f6c-a020-59925a9b0511</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'ach-routing-confirm']</value>
      <webElementGuid>cd68bdb7-a815-4b55-a3e2-6203b90c6153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ach-routing-confirm' and @name = 'ach_routing_confirm' and @placeholder = 'Re-enter routing number']</value>
      <webElementGuid>5d6bd6e6-291c-447b-a7bf-ca560c6a8337</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
