<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Re-enter Account Number _</name>
   <tag></tag>
   <elementGuidId>42f09747-3ed0-4ef4-9ca1-c20b54989347</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'ach-account-number-confirm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ach-account-number-confirm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9008d93d-dfcf-437e-9027-e24521b79800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a7b2469b-a69f-4f15-9c6d-ec0ba151a816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ach-account-number-confirm</value>
      <webElementGuid>ce97ebe4-c6f2-4ef7-a79e-0208513b8de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ach_account_number_confirm</value>
      <webElementGuid>8142e4bc-4406-4bbd-82ce-94a6be8bcd77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>withdraw-ach-field__input</value>
      <webElementGuid>18f8c1c4-8abf-43c1-b901-d6c8e4916a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>63ba1c36-fa0c-43fb-9200-b1c757f6f4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>98127176-50ed-4dbd-897d-3a56e361db5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>713f44e9-4a00-4f58-9ac8-4db6011348a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7424fc1168680e86a3dcacc190c6ac51</value>
      <webElementGuid>d479d4e0-d253-4799-b61f-ae9ee2bda3d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'ach-account-number-confirm']</value>
      <webElementGuid>b459f6b1-cbe0-44b9-9aa4-862335554319</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'ach-account-number-confirm']</value>
      <webElementGuid>b88c1999-f866-4379-9db2-2c2e20b135ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ach-account-number-confirm' and @name = 'ach_account_number_confirm']</value>
      <webElementGuid>6bd1ada5-9b3e-4700-80f6-eb6deea81be9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
