<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_0.00</name>
   <tag></tag>
   <elementGuidId>edfe34cd-495a-44e3-853b-9ca19e1bfdbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'withdraw-amount-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#withdraw-amount-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09af7911-fedb-4ed7-a23e-1c32263cb25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>beb475e3-57d6-41ef-bbfb-8cadc387c9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>withdraw-amount-input</value>
      <webElementGuid>235b7b71-ffc6-4d5a-bb35-6983a1c815c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>withdraw_amount</value>
      <webElementGuid>a0420cfb-ebae-4f42-a793-6383300ebcf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>withdraw-amount-banner__input</value>
      <webElementGuid>a656a4d5-47e1-4eed-a6d9-42eb306f5423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>bbf0df1a-fb02-4d0d-99e8-4ce3d8b96533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>451392c9-cfff-4331-8d89-1415d244b51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0cfd7d75-680a-495e-99c0-491c3a0e8a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter withdrawal amount</value>
      <webElementGuid>0a61ea69-8114-4acb-8658-fc4d4d20703c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e1cc1285-d99b-4bef-968e-d7c17831602d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-966ffdc5f0236444e8216a89f938038a</value>
      <webElementGuid>9b0b260f-cc7b-471e-a86d-b290c7afc356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'withdraw-amount-input']</value>
      <webElementGuid>40cbca43-fc8b-4d19-968d-1ccd1f722c6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'withdraw-amount-input']</value>
      <webElementGuid>9155ce15-eec3-4634-8388-f181617e9cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'withdraw-amount-input' and @name = 'withdraw_amount' and @placeholder = '0.00']</value>
      <webElementGuid>5791dcc9-0578-4cde-9a6f-9a0f994675f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
