<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_paymentAddress_wise_withdrawMoney</name>
   <tag></tag>
   <elementGuidId>7efd37f3-84d7-4ae6-bb87-5fb55f261115</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payment-address</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'payment-address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fbce0c0b-92b1-4638-8fa7-8bd8aa37adc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>withdraw-address__input</value>
      <webElementGuid>8d955901-88ef-4bb1-8e88-7cf7c00bb34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9c32680b-19f8-4e5f-b3db-f3b04e3f376d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-address</value>
      <webElementGuid>b64f7122-275b-4bf8-b74d-71ca8e898ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_address</value>
      <webElementGuid>14f57914-0273-4c19-8a36-4e2acf3b279f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Payment Address Here</value>
      <webElementGuid>ebce3434-a309-4073-badf-56a37cb07c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3624b3a2-906c-4065-a895-3f7482fe02ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>payment-address-hint</value>
      <webElementGuid>fdccfe26-3b84-4bcc-94b2-f07531f2ea45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>755bc428-79e7-4e0a-8dcc-10e10d7e8b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-51b350f56aae2b57a6a99e864238e9ce</value>
      <webElementGuid>b5e79ffc-2cfb-4bee-8f37-47f59b8d0361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'payment-address']</value>
      <webElementGuid>96dc19f7-e50d-4c83-97aa-4d2582cbffd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'payment-address']</value>
      <webElementGuid>287727b9-e36c-4ec5-a02c-fae1be9daebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'payment-address' and @name = 'payment_address' and @placeholder = 'Enter Payment Address Here']</value>
      <webElementGuid>0e265ec8-7103-4f15-94fd-f394b0702d65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
