<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bank Address _</name>
   <tag></tag>
   <elementGuidId>73f910b9-6fff-407d-bb95-acce8593f7b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'ach-bank-address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ach-bank-address</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51be467d-f12b-4de9-bb72-c1eff95472d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>043d48e8-0a02-46d1-a400-167883ef6179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ach-bank-address</value>
      <webElementGuid>65b328e8-9a46-4c38-bb1c-c6311f2cac44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ach_bank_address</value>
      <webElementGuid>96afd81f-30e4-496a-aba0-c3ae862a0774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>withdraw-ach-field__input</value>
      <webElementGuid>d6ed8c36-87c6-42db-bf20-1b30e336bbc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>street-address</value>
      <webElementGuid>68d7f4b2-6d19-40ef-9940-3040713e8bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>2c057c74-1cb1-42ec-9fd9-b06087ff7320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>461bf926-6088-4a27-8d6f-69d2171c4a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-55d7a155d160145d23028b1a16b831b7</value>
      <webElementGuid>2c338d57-0024-40f3-aecb-a9b6784943ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'ach-bank-address']</value>
      <webElementGuid>be7dcd5b-b2c1-4416-8d50-e6a3e5e19c9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'ach-bank-address']</value>
      <webElementGuid>0bc2d94c-c40c-4b70-bf8e-b51c4ceb1e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ach-bank-address' and @name = 'ach_bank_address']</value>
      <webElementGuid>07901ec5-fd0b-4d86-b2e7-72c2639a62de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
