<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Account Type _</name>
   <tag></tag>
   <elementGuidId>c2fbf54c-c5ab-4944-b6c1-92d22d0feb0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'ach-account-type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ach-account-type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8025f64d-607c-43cc-ae74-c775fa8e2f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ach-account-type</value>
      <webElementGuid>bda22270-d0ad-42ca-9010-7db92a87fe37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ach_account_type</value>
      <webElementGuid>0f39fe21-328a-4677-a17f-d8bf5c8c8c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>withdraw-ach-field__select</value>
      <webElementGuid>f6494b89-7b23-4722-9c24-91bbab6b69a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9b5ef5a9-ee9b-4b33-83ff-2f82a471b00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    —
                    Checking
                    Savings
                  </value>
      <webElementGuid>5568aae0-a60e-459a-8ccd-fb532f2accf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fb516eb3d8b5828336e7fd228914a7d0</value>
      <webElementGuid>37565672-0851-4a99-98bf-08a82d6b9431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'ach-account-type']</value>
      <webElementGuid>675efacb-bd9e-457c-88a7-76e961dfdd81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'ach-account-type']</value>
      <webElementGuid>a4278dd2-5959-49bc-934d-08706e27f722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ach-account-type' and @name = 'ach_account_type' and (text() = '
                    —
                    Checking
                    Savings
                  ' or . = '
                    —
                    Checking
                    Savings
                  ')]</value>
      <webElementGuid>d7b56cdb-80e7-4d38-a071-9aa29cbbcdc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
