<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_nextStepBtn</name>
   <tag></tag>
   <elementGuidId>2436f3da-c0ea-45bc-9f58-9972447864cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nextStepBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'nextStepBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>005f357d-5f40-4e6a-b046-392a23bf25cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>register-form__btn register-form__btn--primary</value>
      <webElementGuid>53e0fbf6-385d-4e6b-b9a1-096b4f21511b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1d10c304-9f1f-4cd5-9990-822d3036a534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nextStepBtn</value>
      <webElementGuid>a73808af-b575-4316-b886-8f844a5f2a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Next – go to payment and address step</value>
      <webElementGuid>41bf12de-942f-420e-a9c2-7d1ecae00e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Next
        </value>
      <webElementGuid>9ebaf225-038e-4656-ba4a-3ac969423a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4cb47294e7e392f4228ed5a205131a3d</value>
      <webElementGuid>310eeab0-5849-4914-8e81-be443cc24f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'nextStepBtn']</value>
      <webElementGuid>6198f55e-947a-49ec-912f-9f8409b5e4e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'nextStepBtn']</value>
      <webElementGuid>2282b8d1-10f9-4d1b-a6e8-4635c9be091d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'nextStepBtn' and (text() = '
          Next
        ' or . = '
          Next
        ')]</value>
      <webElementGuid>f74dfb05-eabf-49f9-801f-37561b7c9aad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
