<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_toggleRegPassword</name>
   <tag></tag>
   <elementGuidId>374f026b-6f5f-4cdf-89bd-bd233bb392b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toggleRegPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'toggleRegPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>869e11f9-9136-42d8-a7d3-baa310b74aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>register-form__eye-btn</value>
      <webElementGuid>029325ed-b362-45bf-8b2f-c2b525fa9aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>616a59f6-4178-4c95-bc54-976eeede56f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toggleRegPassword</value>
      <webElementGuid>9aaa4fae-b4f0-477a-99d4-b5ee8ba95fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Toggle password visibility</value>
      <webElementGuid>6f32f430-8dcd-4c25-9a72-3696eadb3d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>96a3ede8-e2ce-4423-9259-28176ad20486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b8695042abedc6293bd887588b106027</value>
      <webElementGuid>737ebc85-d982-4e3f-bea6-dd2c055bbb33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'toggleRegPassword']</value>
      <webElementGuid>ee26022b-404a-44b7-a3a6-23075e4bfea3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'toggleRegPassword']</value>
      <webElementGuid>bf93191d-6739-4602-9c5a-a4b99ee8add3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'toggleRegPassword']</value>
      <webElementGuid>1a9ab283-e4b4-4aa1-8c4b-c94188332181</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
