<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip_Postal Code _</name>
   <tag></tag>
   <elementGuidId>3d2929d1-9669-411a-8080-ae56b7c0de33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_card_zip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_card_zip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57917bbd-1dd7-498d-9bfd-0aca193f197c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ddd0286-a393-4392-a5ca-a74756cffd4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_card_zip</value>
      <webElementGuid>c3b6c807-6efc-4732-91ee-f4a8d44ab332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Zip/Postal Code *</value>
      <webElementGuid>f9525341-c201-4c15-bc2a-647c66f219c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payment-form__input</value>
      <webElementGuid>75afe302-03a5-4151-85ae-ee07d5dbba0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>postal-code</value>
      <webElementGuid>39d51941-d339-4cfe-9d0a-056f86225d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>09a6e656-95bd-46fb-8af0-b8e09882da00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6b66d8d3-3cf3-419c-92c0-11b780b844d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-13f3b8e1e5ef36a80927a5404ad31320</value>
      <webElementGuid>2c8872e9-3d96-4574-9582-40a13a783254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_card_zip']</value>
      <webElementGuid>a7c4b699-4016-4145-a2cc-0a12503fcdb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_card_zip']</value>
      <webElementGuid>4d99d085-9794-4a68-84cb-93ca2fb48462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'id_card_zip' and @placeholder = 'Zip/Postal Code *']</value>
      <webElementGuid>24f2f440-94c7-4c6c-9548-56e68166e9be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
