<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Email</name>
   <tag></tag>
   <elementGuidId>d3809f2d-f97c-47a4-801d-47c08717dc19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cfmEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'cfmEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c703eb01-88a2-4605-92b6-de0fd5f5a743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cfmEmail</value>
      <webElementGuid>dbdc9480-813f-48ee-b0cc-a418503baaf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>54a727cd-d641-4f18-896f-4648093286bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vEmail_confirm</value>
      <webElementGuid>968e38ef-db2b-4534-815d-c6b13dc95bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>44e990a8-84fd-4562-a6fc-1f09cf6c165d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>b6267f01-76d3-419e-8ebd-0de67d5b2bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>register-form__input</value>
      <webElementGuid>7760109d-a564-4084-ac5e-7a967cca9809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm Email</value>
      <webElementGuid>446a8192-f8b0-44bf-840e-e433271b8c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>08b7e8b3-9496-4bc9-941d-37fa2bf46d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>929a7fdf-030b-4f10-bc02-bfa3ba7013de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-154ec95bc11833df7f0842c83ee08722</value>
      <webElementGuid>bd7a47a5-bdda-4454-bffe-3b7817e507a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'cfmEmail']</value>
      <webElementGuid>2edf422b-0f90-4963-8923-6428c0be6274</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'cfmEmail']</value>
      <webElementGuid>d1cbac9b-24a9-4b4b-95f9-e488d03ad327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cfmEmail' and @type = 'email' and @name = 'vEmail_confirm' and @placeholder = 'Confirm Email']</value>
      <webElementGuid>c297c0f3-2ff0-47c8-b752-246c8de6b85c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
