<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name on Card _</name>
   <tag></tag>
   <elementGuidId>0fb81e6d-43a1-46cb-a4de-92e319b72ed7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_card_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_card_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abca5914-fe9d-4f84-ad7a-4eca9d18aec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c5429ef-d871-4862-a3f2-297fe12e7c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_card_name</value>
      <webElementGuid>a5069d01-5cfd-469d-86ec-e7bc35b68b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name on Card *</value>
      <webElementGuid>f243c750-af77-4be2-9d3a-936b96413ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payment-form__input</value>
      <webElementGuid>b882dfac-0a4e-4033-8f76-b8b4ecea03e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-name</value>
      <webElementGuid>d642e76e-20d0-41cb-9ba3-ab64509140c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9bc0d839-6107-4af0-9548-fee253c326e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-99a8c40a463ee3e05b7045661a83575e</value>
      <webElementGuid>fe07457c-f295-40df-9f6d-56e92d6f257d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_card_name']</value>
      <webElementGuid>4756348e-cc61-4cdb-bcbb-6c54c583ca13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_card_name']</value>
      <webElementGuid>ef18915a-3579-41ca-a9c2-227c84fd25a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'id_card_name' and @placeholder = 'Name on Card *']</value>
      <webElementGuid>f9f89216-72b4-4143-b03f-8e81470e68a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
