<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name</name>
   <tag></tag>
   <elementGuidId>7f398d85-60dd-4141-af3f-39b14f6ec31a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chk_fname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'chk_fname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a155a8b-9cac-46b9-b9b6-85ef64ec9b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e388f18c-7b42-4b0d-a26d-b4c56e01a671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk_fname</value>
      <webElementGuid>7c48a4ab-c108-4b40-af3f-8b1926243bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chk_fname</value>
      <webElementGuid>530c915f-ec9e-4a04-9078-32e41d1e5fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>a8fe22d2-2ac1-4fc5-92c2-0da3a563b114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>register-form__input</value>
      <webElementGuid>156a69ef-9f11-444c-ae71-c9b1c6c16ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>7c4b9229-1ad0-4e6d-bfaa-922d84a5b786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>given-name</value>
      <webElementGuid>4e0cc96b-8d20-41d4-8e1f-20b517a4bc9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c05bb594-9661-41c7-bc49-57983aab4fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-05c81499c17728b93de3cfceb8cf7f1e</value>
      <webElementGuid>4c097e90-a54c-4ef3-a7d6-6192aa16ce27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'chk_fname']</value>
      <webElementGuid>fc4cf2ea-7edc-419a-9a70-85b97e98a252</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'chk_fname']</value>
      <webElementGuid>87cbb024-f7de-4086-9818-82323b15ef62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'chk_fname' and @id = 'chk_fname' and @placeholder = 'First Name']</value>
      <webElementGuid>9d48beb0-c046-467f-b9ff-dbc294a50745</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
