<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City _</name>
   <tag></tag>
   <elementGuidId>6ca437b2-4d36-41f1-bcd4-32a88f101b70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_card_city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_card_city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd620184-73cc-457d-b786-157b58df3c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e39b227-a275-487c-b90b-fa569e6238dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_card_city</value>
      <webElementGuid>a82393c9-9c9c-404c-a12e-6abd4c077900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City *</value>
      <webElementGuid>ff760669-0076-4d60-87b3-695964716681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payment-form__input</value>
      <webElementGuid>4540b5bd-a293-436b-952a-fe4f9274647b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-level2</value>
      <webElementGuid>729df4c5-3cda-409f-9f2b-b35114539705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>959c9705-094b-4839-970b-a8132583a75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2044114e141ff3cff923a6e0d383d1a2</value>
      <webElementGuid>948f1361-0617-4878-81b4-600b3206bd98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_card_city']</value>
      <webElementGuid>ce0ba1e7-6886-4cad-93a5-9120ece81a9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_card_city']</value>
      <webElementGuid>c0efbb3e-9e3d-4d53-b4a5-63bdcc62acc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'id_card_city' and @placeholder = 'City *']</value>
      <webElementGuid>31a5e612-2648-49e9-9585-b2f9477686de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
