<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter Referral Code</name>
   <tag></tag>
   <elementGuidId>50b8d3f1-63b1-4278-a7ac-1b167372d250</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'search-box']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b8fe21e-01d7-4e32-8446-09a24d56e82d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db755261-90f3-4aa0-8896-f7f05bf127a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>orucode</value>
      <webElementGuid>5211c969-fe10-4f4f-bcb1-88cb832a19a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>1c76f7e0-68eb-4b7f-9789-bb6872fc6a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-box</value>
      <webElementGuid>d20698a2-0511-4bec-999e-448879a66c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>751f397a-1120-474c-b694-538e196caf4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>register-form__input</value>
      <webElementGuid>88be0f1a-49f8-4b74-bfaf-94817ef06e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Referral Code</value>
      <webElementGuid>d001aecb-4f65-4708-98bd-965379aa014a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fa9455ca-fda4-423c-8e3e-a8b834ed6d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e7965aac5cd8eb00ff6c442569ce33e4</value>
      <webElementGuid>ae3f87c0-7386-463a-af8f-a0e9baa4e825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'search-box']</value>
      <webElementGuid>5c0a77ff-49d0-4ba9-9f1e-5b4b7b1bf361</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'search-box']</value>
      <webElementGuid>6fe5cd76-5f1b-4f9d-8476-efb19f0825be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'orucode' and @id = 'search-box' and @placeholder = 'Enter Referral Code']</value>
      <webElementGuid>5c4830fb-e06f-48c7-bbe8-f755a1c1e595</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
