<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address _</name>
   <tag></tag>
   <elementGuidId>00d26687-86c6-40fe-9513-8d9325c226be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_card_address</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_card_address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffbe3c2c-9e00-4e78-9ff9-c92f36c1f41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>51dbd626-0afc-4098-ae26-01f1663b6f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_card_address</value>
      <webElementGuid>af63aab4-3933-49a9-83b1-4df0861f3a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address *</value>
      <webElementGuid>117d4c4f-06b1-48cf-9909-25d671830179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payment-form__input</value>
      <webElementGuid>efb7527d-6216-46df-bba9-54eac854e0cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>street-address</value>
      <webElementGuid>a59a37df-9ec6-4bb0-a4bb-cbf9bb8736ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>40f560ff-7c0b-46d4-ac4d-1eaf09115a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-87b4ca7c563e3ca450b31f358b6c6fec</value>
      <webElementGuid>8eb3d05c-27df-48a0-8d36-04f364b7ab20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_card_address']</value>
      <webElementGuid>69942f61-833c-4d1a-957a-4b8d5e8ebc89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_card_address']</value>
      <webElementGuid>2e1b878d-4516-4509-9ab8-e1e4c40eb7e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'id_card_address' and @placeholder = 'Address *']</value>
      <webElementGuid>1cc61a2e-b59e-4dee-a352-68da7fbaa551</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
