<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___1</name>
   <tag></tag>
   <elementGuidId>46ccd808-879d-422c-85ca-311112bec587</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cpwd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'cpwd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>095e2deb-ce9b-43d0-b135-0500d5165fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cpwd</value>
      <webElementGuid>ebbbff5a-2ee4-499e-b56b-09b205fcce96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>5b5d0cc5-2ae9-49f3-9ef3-4d42151406d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vConfirmPassword</value>
      <webElementGuid>4c5b52f5-d0b2-45cd-a921-230e250a0e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>fc735f0d-5969-493c-a291-1632f6b059a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>register-form__input register-form__input--password</value>
      <webElementGuid>0a9aa8de-b8ed-4bfc-9a55-c78d4e33e2ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>************</value>
      <webElementGuid>8830c79c-b729-4ce9-af86-97c402c16871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>f932ae65-a525-463d-983b-bd3a54d5e8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>36d765df-21a2-48ed-bfee-db0797bc84af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9b089f98ff8ff1b438282f7ff36770d1</value>
      <webElementGuid>0a8c354c-fe85-4921-a34d-df0b0e4643ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'cpwd']</value>
      <webElementGuid>2ee504e9-c836-4059-803f-06109254dbdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'cpwd']</value>
      <webElementGuid>c875d53b-e659-4485-85e0-49eab04e8788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cpwd' and @type = 'password' and @name = 'vConfirmPassword' and @placeholder = '************']</value>
      <webElementGuid>ba413ba9-f2f2-414c-9cf6-52adb551663f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
