<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number</name>
   <tag></tag>
   <elementGuidId>9246eaed-a444-409c-a610-3730e47acc3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vPhonenumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'vPhonenumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2be3de81-decc-4d1a-9a87-187c4a279a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>register-form__phone-input</value>
      <webElementGuid>22d679bd-4d77-469b-8bd9-a050de9f00a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>e28b2b07-5774-4619-a6f2-9d0ee67143db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vPhonenumber</value>
      <webElementGuid>7b05d75e-299b-46f9-9080-205781b24d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vPhonenumber</value>
      <webElementGuid>8885c6b2-de4d-4000-9b5a-0996b9afa2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel-national</value>
      <webElementGuid>60d5aeb7-44ea-4679-97c7-ec5a2ece72af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b7ab69da-7b14-40d2-bcfa-84255525ff9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Phone number</value>
      <webElementGuid>fa3e6430-6fea-44a9-b6b2-d80b49e0e479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3778eb050ff50366dbfd165d85251ee3</value>
      <webElementGuid>8feef3e1-7a28-4aa2-bed1-e4a1c14189d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'vPhonenumber']</value>
      <webElementGuid>d4f22561-b6f4-4c09-9817-73800e63591c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'vPhonenumber']</value>
      <webElementGuid>0af3d2d1-af60-41c5-bc6f-d4785121c670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'vPhonenumber' and @name = 'vPhonenumber']</value>
      <webElementGuid>e7ebc0f2-8a38-4dc4-a266-ef15157e9c42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
