<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_By selecting the monthly subscription optio</name>
   <tag></tag>
   <elementGuidId>e5017866-8843-44c1-bf10-4dbddbebc520</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.payment-form__checkbox-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' payment-form__checkbox-box ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c416500c-1808-4cc0-bbcd-f35f984fb3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payment-form__checkbox-box</value>
      <webElementGuid>a1ce9a99-a645-4f6a-bc28-0e11afca7ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>51834b2d-cd40-4b88-bd96-3b3e161ea068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7984af65547ff5a22558848f77eecbfa</value>
      <webElementGuid>40e0a5a5-4fb0-4796-ae46-19dcce989fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' payment-form__checkbox-box ')]</value>
      <webElementGuid>efe40b39-96fd-478f-9058-a22c851916b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' payment-form__checkbox-box ')]</value>
      <webElementGuid>ddc7085b-8166-4fa3-b496-5d52d958de94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
