<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_vmodal-verify</name>
   <tag></tag>
   <elementGuidId>34deb767-553e-497e-9603-399c4749176a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vmodal-verify</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'vmodal-verify']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>042c4151-377a-4747-a52c-daa475f8099d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vmodal__verify-btn</value>
      <webElementGuid>9cec323c-09e2-48b2-9e26-af7689f07197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vmodal-verify</value>
      <webElementGuid>3e54f2c8-1c55-4686-9bc8-3da8e774f258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>501f6a19-7c3b-4e3a-bd69-f356fa8d500d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1cd7e2f0-0cfd-49e1-a0b6-ebb0437bec49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify</value>
      <webElementGuid>33660300-8915-48eb-b9fb-990adbe1129f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4a1bdbe775ebf9a85ab9075ae9478408</value>
      <webElementGuid>0308ab1b-7ff8-4591-8874-209e02451067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'vmodal-verify']</value>
      <webElementGuid>24f199b8-fb71-48b5-8955-e8bb80481ab9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'vmodal-verify']</value>
      <webElementGuid>496a6619-3e15-432a-a697-27a77c880b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'vmodal-verify' and @type = 'button' and (text() = 'Verify' or . = 'Verify')]</value>
      <webElementGuid>b15a9814-ce64-4844-b252-bcc2f99b037a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
