<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_0000 0000 0000 0000</name>
   <tag></tag>
   <elementGuidId>a874aa7b-0692-4af1-81c4-28ce2402d164</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'card_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5b4055d-ccf2-4429-885e-dddf19df488b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fsu-form__input</value>
      <webElementGuid>329fda73-c5c1-46c4-836d-a00c56a94b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ef84dc2-1d66-4862-8524-0210ae41462a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card_number</value>
      <webElementGuid>46ee7518-7bf3-4685-9b39-b1e93e6ac850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0000 0000 0000 0000</value>
      <webElementGuid>b199ca97-7fea-4725-ada6-b1af2b2a0eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>3e6b2787-e8fa-4266-acc9-be4d723082e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Card Number</value>
      <webElementGuid>74a99070-3836-4615-96ee-16c6c21bf64a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>588c979a-852a-4920-8386-f997ae1907a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-number</value>
      <webElementGuid>24cc355a-fd7a-4e65-80fc-01824f8d68af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4b709284f32c973ee075b56ba78fc431</value>
      <webElementGuid>b16e117a-a77f-4825-8c00-e00b04095ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'card_number']</value>
      <webElementGuid>99632459-0da8-49e8-9aea-5a652d0b6ecc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'card_number']</value>
      <webElementGuid>cae268ae-a135-4111-828e-67e56f7861d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'card_number' and @placeholder = '0000 0000 0000 0000']</value>
      <webElementGuid>961c9e75-23f1-4932-a8a2-f1b0e6cb5682</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
