<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_token-admin-security-key</name>
   <tag></tag>
   <elementGuidId>73c8da4a-ce60-4b5f-a27e-ad6a3dec82cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#token-admin-security-key</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'token-admin-security-key']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5526faca-d369-4ff1-9433-780672cd5fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>token-admin__security-input</value>
      <webElementGuid>2ace7a23-e3d7-4879-a818-47bc142118df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>token-admin-security-key</value>
      <webElementGuid>018b4638-f62c-4d22-a7f4-0b2954777797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>11d0b569-2c6b-469e-9506-45f2ab06bead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3e715ae5-dc3a-4ba6-8da7-8bd6acd10032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>token-admin-security-key-label</value>
      <webElementGuid>18f79b4f-6903-408b-b76d-c57d18ca0820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0fe214ce-5794-4a12-bb99-7fcad0b7228e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>petPezl/sHovj8QFTQy+ug==</value>
      <webElementGuid>fabfb9d6-c4f6-4c69-98df-abd91a36a96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a2815e1694e31368fc64271269d877f8</value>
      <webElementGuid>f9169882-950d-4a64-a4f0-31ddee58fe57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'token-admin-security-key']</value>
      <webElementGuid>b8718e9b-b0c0-4817-807a-fe836006d2f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'token-admin-security-key']</value>
      <webElementGuid>9ce99b8d-0f3f-47e1-a79b-245956e4b613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'token-admin-security-key' and (text() = 'petPezl/sHovj8QFTQy+ug==' or . = 'petPezl/sHovj8QFTQy+ug==')]</value>
      <webElementGuid>f710ed72-8f09-493f-9851-a478b05ee58f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
