<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_totalTransactionCount_tokenTransactionHistory</name>
   <tag></tag>
   <elementGuidId>dba3d4b4-5d44-4853-9dbb-d9ff69dcaa0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.token-admin__results-total</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' token-admin__results-total ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2221bf76-1127-45b0-9968-f5668952aecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>token-admin__results-total</value>
      <webElementGuid>1a5b8b60-72d1-48ff-819b-a7963a474d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>133</value>
      <webElementGuid>7e6b38c3-e5bd-4c53-95cb-b1f898359f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9a699f2bb82f80b4c8388ae0a1394061</value>
      <webElementGuid>f9ed0816-5091-4eb7-8278-f9b1842b271e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' token-admin__results-total ')]</value>
      <webElementGuid>19d22557-e7a9-4938-b426-33a18e13aded</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' token-admin__results-total ')]</value>
      <webElementGuid>6cf46d8c-7935-49d2-abbf-b3a54bb676af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '133' or . = '133')]</value>
      <webElementGuid>e41f88a3-7639-4d56-ac62-60296fcbee99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
