<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm Transaction</name>
   <tag></tag>
   <elementGuidId>7292e41c-5504-454b-9595-cead06bc9e9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.walletn-pin__confirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' walletn-pin__confirm ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a05aa90-cab0-49ab-81a6-1e706fde2042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>walletn-pin__confirm</value>
      <webElementGuid>c8853476-be95-4d06-92a5-558787caaa9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0a23aae9-00d9-4823-ba62-2fe1ca5eb9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm Transaction</value>
      <webElementGuid>2409f0b3-e4ac-4949-a91e-ff1888eba4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3d735eca5bf53a14ecbbfc6c2a78d507</value>
      <webElementGuid>876ffcc0-c90f-4be0-841e-15fa2a69f105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' walletn-pin__confirm ')]</value>
      <webElementGuid>6b6aac2c-0576-4835-9bb6-6675ad63d2e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' walletn-pin__confirm ')]</value>
      <webElementGuid>98908a56-44f1-45a0-9b87-3965367f192a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Confirm Transaction' or . = 'Confirm Transaction')]</value>
      <webElementGuid>1edc2777-f515-4661-a98b-11bcbacfbd87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
