<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_toStep2</name>
   <tag></tag>
   <elementGuidId>c44f0b5f-c033-4298-a74f-3e9acf758971</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;Continue\ to\ review\ your\ deposit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = 'Continue to review your deposit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ac141f78-b631-48d4-b0da-dbc791c676fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toStep2</value>
      <webElementGuid>f025d75e-b00b-4e41-bbaa-f8052aa5ac8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>59ca92a2-c17f-44a0-89ed-9454dcb37827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>deposit-cta__btn</value>
      <webElementGuid>116d7db0-04a2-4d55-9534-2a2dc9b4e032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Continue to review your deposit</value>
      <webElementGuid>02cd9c59-2cb5-4e0b-b80a-8ce534fd33d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>803896dc-8c59-4e6a-ab00-a50f78b1f591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              Continue
            </value>
      <webElementGuid>cef1cf29-9804-463d-9903-c34135f024c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a8897f63d18cc36aa5eba6f149e2a557</value>
      <webElementGuid>3f28116a-32e4-44e1-be2c-9917c0ae9ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Continue to review your deposit']</value>
      <webElementGuid>585fde09-80f7-4e99-a831-e47ddc98c6b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Continue to review your deposit']</value>
      <webElementGuid>f154c992-49e0-44d3-af1c-fc971bd21682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'toStep2' and @type = 'button' and (text() = '
              Continue
            ' or . = '
              Continue
            ')]</value>
      <webElementGuid>5296c8e7-2fb9-447f-b96d-82b28311c96c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
