<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_vmodal-verify</name>
   <tag></tag>
   <elementGuidId>1c21ec83-2651-4849-ac50-2a97e6c10dda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vmodal-verify</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'vmodal-verify']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dac75c03-0ba9-48e7-a71b-f49a4d7dfd91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vmodal__verify-btn</value>
      <webElementGuid>4361cdfd-8642-4cbc-abbb-bb87f13117f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vmodal-verify</value>
      <webElementGuid>47cf971e-69fc-4805-a502-0f1fc9ecd037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9c9bf005-638a-459d-ac30-a79e17be4704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8a0d7f78-8ba7-47fe-aeee-8dc4d3cd5bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify</value>
      <webElementGuid>bb85ee28-83d2-42e7-ba06-1534670d6910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4a1bdbe775ebf9a85ab9075ae9478408</value>
      <webElementGuid>17365d52-08fa-4baa-ab34-c68540f15d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'vmodal-verify']</value>
      <webElementGuid>1b262655-c27c-4d93-bef2-763064c34305</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'vmodal-verify']</value>
      <webElementGuid>5eb4b512-be6b-4e83-ac8c-948109151dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'vmodal-verify' and @type = 'button' and (text() = 'Verify' or . = 'Verify')]</value>
      <webElementGuid>76aa0ad2-9408-4a8f-996a-b0d3eeffecdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
