<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_John Doe</name>
   <tag></tag>
   <elementGuidId>b73babed-5258-4390-bb27-f05eac775ca3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_card_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_card_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b3da963-201d-4756-83db-b101b4f62031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>walletn-input</value>
      <webElementGuid>bea86833-d707-4ada-9186-f65587b3ede6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_card_name</value>
      <webElementGuid>ca3bcfa0-3127-49cb-8dd1-1c3daa6dd404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c2540e88-f052-46cc-bc95-56b0d562a6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>John Doe</value>
      <webElementGuid>04d2cffa-cab7-479e-ab50-99b1aebbc918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Name on Card</value>
      <webElementGuid>f456058f-bcf7-4dc9-86fd-1e4a3025952c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-99a8c40a463ee3e05b7045661a83575e</value>
      <webElementGuid>2b2d9679-8d66-45f4-9fd9-be8ebcb0bf47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_card_name']</value>
      <webElementGuid>361a955c-c946-41a9-9b10-5ade654105d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_card_name']</value>
      <webElementGuid>4a9f95f9-9072-43e3-8e27-f58851ec2077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'id_card_name' and @type = 'text' and @placeholder = 'John Doe']</value>
      <webElementGuid>dda75347-3cb3-4dc7-b1fa-180490025cf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
