<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_123 Main Street</name>
   <tag></tag>
   <elementGuidId>6f567aec-e3f9-4977-abfa-7b576afebc37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_card_address</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_card_address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01c83b07-db98-4dab-938f-3e073601145f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>walletn-input</value>
      <webElementGuid>088192d3-b0e1-4906-9863-97c2f825b7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_card_address</value>
      <webElementGuid>5894a541-9ad9-4ba7-886c-dc0ed5c6c52c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>84ecdb95-d02f-4788-8925-c8194c9d47bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d07ec552-463b-4e69-81d2-fee38c2f7047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>123 Main Street</value>
      <webElementGuid>1aa5f3ea-e4a1-474b-adc8-56440bb332d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>7d0bd074-0c16-44f2-b1bb-a883a799a506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-87b4ca7c563e3ca450b31f358b6c6fec</value>
      <webElementGuid>6178d590-7bbd-482f-aaae-c69a3d41ee3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_card_address']</value>
      <webElementGuid>56de379c-4f2b-4ab7-aae4-37a6b5db1aae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_card_address']</value>
      <webElementGuid>97605e81-8098-4679-b6be-179ab1c1310a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'id_card_address' and @name = 'address' and @type = 'text' and @placeholder = '123 Main Street']</value>
      <webElementGuid>c30643d7-40a8-4fd4-b19b-8db8843e790e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
