<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MM _ YY</name>
   <tag></tag>
   <elementGuidId>0b06ff4c-2786-4717-b25f-b879471feb61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_exp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_exp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>165e4cd3-3e93-4ca8-be0c-aacf40d4dab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>walletn-input</value>
      <webElementGuid>53d6326e-ef0d-466b-9715-ab9d80ef8b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_exp</value>
      <webElementGuid>03b9d709-0eed-433a-b2d8-3d899de748b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>26e93bbe-a79b-43dd-b442-08c6d3afdb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>19664e37-a5f1-4c2e-9025-0a8692e69711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>d61fc561-9829-4c53-9508-d7225e6bd745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM / YY</value>
      <webElementGuid>a105559e-a789-40f7-9ad0-45e3eb14b8bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Expiration Date</value>
      <webElementGuid>290c3495-3394-4a8f-893b-0c23740fd4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>8472b024-8340-4678-bb9a-98b5fa7fb4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1faa4197dea9d143f0d777316183ea4d</value>
      <webElementGuid>5cb1f087-ce14-46f7-866b-7a63420a1f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_exp']</value>
      <webElementGuid>4f977e2a-7784-488b-a907-321c4bedf8d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_exp']</value>
      <webElementGuid>cdf94bc4-a6c1-406e-b657-4024ff51b06c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'id_exp' and @type = 'text' and @placeholder = 'MM / YY']</value>
      <webElementGuid>5204d4d4-5685-49e7-85fb-45e2b72f7378</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
