<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_10001</name>
   <tag></tag>
   <elementGuidId>a1a9610c-da47-40b8-b7a3-4ab77a0bf0d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_card_zip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_card_zip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34074026-3222-4e83-ac0a-dd1952207064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>walletn-input</value>
      <webElementGuid>39e3117c-8282-4f20-b1c6-c36edb0a9cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_card_zip</value>
      <webElementGuid>5187d99d-5702-44e9-b2e1-4b121df0a70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5e015a4e-803f-4bb7-bc6f-96388cd27ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>10001</value>
      <webElementGuid>bd673d6b-3489-419d-bcda-2db8feb114e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Zip or Postal Code</value>
      <webElementGuid>9c9249db-07d5-40ac-8e9b-3cffefa4948d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-13f3b8e1e5ef36a80927a5404ad31320</value>
      <webElementGuid>6627fbfa-b133-441d-bcfd-c3b8471f4634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_card_zip']</value>
      <webElementGuid>0e079052-c797-4374-a2c5-0d1ec921edca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_card_zip']</value>
      <webElementGuid>e5bb6664-87b7-40b8-b394-77fc6683f0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'id_card_zip' and @type = 'text' and @placeholder = '10001']</value>
      <webElementGuid>9d4aec1e-d0ec-4173-828b-deaeffadc756</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
