<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_1234 5678 9012 3456</name>
   <tag></tag>
   <elementGuidId>e9fe0e39-5e76-45e3-9e64-04dde07b1242</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_card_num</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_card_num']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d90e609f-c3bb-44b1-975e-16c1cb660a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>walletn-input</value>
      <webElementGuid>1c365a20-2b69-4fbe-903f-67a9003e9f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_card_num</value>
      <webElementGuid>8ff41ca3-57db-45a0-b3c5-839224014539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83f9de68-b8b4-43ad-ae16-784a809d0310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>cd510d80-d8a7-4ce6-9622-22461d0395f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1234 5678 9012 3456</value>
      <webElementGuid>37183839-6636-445b-8c95-7fa2dff8846b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Card Number</value>
      <webElementGuid>7ab25767-50b0-4510-b80c-cd4fb5b90186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e687ac70a3ad5572ec30a2d06e5031ca</value>
      <webElementGuid>22e12066-9160-450b-ad20-c08c4bae3e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_card_num']</value>
      <webElementGuid>11d41804-68bd-404e-826f-f39b58235ba3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_card_num']</value>
      <webElementGuid>c07a8bf2-36d1-46c9-8a28-e2bd5d98a30f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'id_card_num' and @type = 'text' and @placeholder = '1234 5678 9012 3456']</value>
      <webElementGuid>ea899224-62db-483f-9e84-59508b91e705</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
