<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_0.00</name>
   <tag></tag>
   <elementGuidId>458678ea-dd94-4b1c-b9f7-b71abcde1feb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deposit-amount-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'deposit-amount-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4505b60-1c69-46ca-b7a6-2cdca06759b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d37dafd6-12ba-4f10-a39c-37efdcb36a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deposit-amount-input</value>
      <webElementGuid>5f4794bc-f605-4a10-994d-38b5e6ab4248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deposit_amount</value>
      <webElementGuid>e2812ed9-7dcd-4285-84e1-d77ef025b059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>deposit-amount-banner__input</value>
      <webElementGuid>463eb082-ca46-4863-aa57-650142cfb422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>ae257674-bfae-4271-83ca-7f2a80cc1131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>8d8aac5a-80db-4c56-8bf3-90fd8d2ae425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>45d31482-6188-4e33-abc3-8cca81f74d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter deposit amount</value>
      <webElementGuid>184578f7-7aea-48c2-a320-871611909388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3c62d644-8a2e-45ed-894b-e4364555102c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-43e30fb543a8cc72af280ea258febcaf</value>
      <webElementGuid>69a30563-9c7a-4477-b28b-fc991c04fd6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'deposit-amount-input']</value>
      <webElementGuid>0ba02acd-ec5c-43b3-ac81-412fe5125cbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'deposit-amount-input']</value>
      <webElementGuid>29cbf05f-4f2d-4832-b731-4b529c0d4305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'deposit-amount-input' and @name = 'deposit_amount' and @placeholder = '0.00']</value>
      <webElementGuid>e917f51c-a919-4b68-97fb-087219e9a1ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
