<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ycptcpt</name>
   <tag></tag>
   <elementGuidId>96a7e5b8-8317-429b-a86d-ea590f055f2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ycptcpt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'ycptcpt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ae7cc33f-537b-480c-bc37-84ae8379db87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ycptcpt</value>
      <webElementGuid>f472354d-f068-47b6-b4e7-9fbc7efefc4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>ea897ad2-398f-4860-9443-3d1e22b0bf5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-18b98200361257a17ad6ffda12a5e756</value>
      <webElementGuid>2fc4d5e7-a205-42e3-8fa1-90a0579afb09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'ycptcpt']</value>
      <webElementGuid>bef78eab-b7bc-44ba-a1ce-6fd8f3a6afd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'ycptcpt']</value>
      <webElementGuid>ea2b416b-3a93-4c4f-b9ce-c01cd04393f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ycptcpt' and (text() = '' or . = '')]</value>
      <webElementGuid>98a2c013-5d13-4734-9d00-12afa5844832</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
