<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit voucher</name>
   <tag></tag>
   <elementGuidId>54dc8836-0807-4e59-a258-06e5a3920cc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;Edit\ voucher&quot;].edit-btn[data-name=&quot;TestVoucher&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[@aria-label='Edit voucher'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6284bd38-5634-4934-b7e6-68d094880c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>482767c3-4db7-4e78-b84f-0e7ea47a9d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vouchers__action-btn edit-btn</value>
      <webElementGuid>acce92f5-ef32-4b58-9351-b05647786018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>TestVoucher</value>
      <webElementGuid>774bdfd4-7f3b-4f1f-a4cd-9bc860275526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>https://beta.faradconnect.net/register.php?vc=testvoucher-4471</value>
      <webElementGuid>d629981a-90ce-400c-92cd-d6641decc97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qty</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e50aada3-dd07-4ecf-b0fc-53b5646e7287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-amount</name>
      <type>Main</type>
      <value>6.45</value>
      <webElementGuid>5440cda7-54de-4892-9cff-01923a73a790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-totalamount</name>
      <type>Main</type>
      <value>12.9</value>
      <webElementGuid>9f7e7651-6888-4cff-94b1-1d4202ecbf30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-include</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>42a28a9f-7eea-4b3b-8edf-e44a5f040dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-codetemp</name>
      <type>Main</type>
      <value>testvoucher-4471</value>
      <webElementGuid>069c9a5c-7991-4770-96f2-3c458efaef06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>122</value>
      <webElementGuid>a0eef6fc-7858-4300-a413-fe89f0bf509c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-stat</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e023767f-406d-45a2-a6fc-b981be38d90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Edit voucher</value>
      <webElementGuid>50259769-3645-4af4-ba42-2a055ad1fe63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a41006e9-ed0e-4b62-b87c-3720c76b1dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7ff0c9429e11d842060a326004fd18e2</value>
      <webElementGuid>a674a50d-aac4-4176-9ce9-c3f3e494e468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@aria-label = 'Edit voucher') and @class and contains(concat(' ', normalize-space(@class), ' '), ' edit-btn ') and (@data-name = 'TestVoucher')]</value>
      <webElementGuid>96269133-ac46-4371-a748-8ed28b56cc5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@aria-label = 'Edit voucher') and @class and contains(concat(' ', normalize-space(@class), ' '), ' edit-btn ') and (@data-name = 'TestVoucher')]</value>
      <webElementGuid>768535ad-b6a8-4cb3-94e4-9366612ca5a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>0cd3dbb2-b1c0-46c8-8d5e-5a8d0c157f38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
