<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Number of Vouchers</name>
   <tag></tag>
   <elementGuidId>14535fca-3aaa-4772-bd55-07c3aa40fd5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#voucher-quantity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'voucher-quantity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5788ea1a-0178-49ff-9e3a-9600b46a8767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>voucher-field__input</value>
      <webElementGuid>95d7eaa9-e08c-460c-8fdf-5fc770af7177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c0c6f254-64b3-440c-bd06-85aa7e913496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>voucher-quantity</value>
      <webElementGuid>d18f2b8c-75a4-453a-9a65-d5ae7c0f7904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>voucher_quantity</value>
      <webElementGuid>7fe2f724-4c74-479c-8b6f-15687940341a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8af157c3-0df1-4ffb-a5f2-d1f4aac3a0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>12b770bf-62d8-44c6-9efa-c7dd3154a3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0980198b-b551-47c1-8426-c8e2b8624503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-400fea887fe553c1d16a4dfafb218d3d</value>
      <webElementGuid>1d8447de-4da9-47ab-87d2-ea200ca266a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'voucher-quantity']</value>
      <webElementGuid>bbebcffb-c4d9-4e1f-9c49-8bef27b1c852</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'voucher-quantity']</value>
      <webElementGuid>d000448d-2f3f-4f76-b7af-b10ef96a9306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'voucher-quantity' and @name = 'voucher_quantity']</value>
      <webElementGuid>8eb724fd-6662-4464-91d3-93af22017dc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
