<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_voucherNameCreation</name>
   <tag></tag>
   <elementGuidId>864dba4c-528e-4985-91b0-21e5c98f0b2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#voucher-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'voucher-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d769785a-2832-4d09-9d5c-e88ef9352d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>voucher-field__input</value>
      <webElementGuid>545d98fa-c648-4eba-bc87-fd0dc8a7dec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a650548a-79fd-4cdc-b183-f891a3a20b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>voucher-name</value>
      <webElementGuid>6ef8656d-fcc3-477d-aa31-0c0aadc8ccf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>voucher_name</value>
      <webElementGuid>cb03cc5e-61fc-43e2-bb8a-5f63dcba4a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g., New User Welcome Voucher</value>
      <webElementGuid>c6b193a1-db02-481d-8b14-618173dc20a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>aed0d514-0093-4443-8816-5db5a0088b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2c21b851-045b-4f3f-8066-78f89d8853c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c5a7b289f06629a62e84c68c28d5bb43</value>
      <webElementGuid>faf0e45d-3d69-47d4-8dee-c769882d6ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'voucher-name']</value>
      <webElementGuid>8f5c22d2-87a5-46f1-9ba5-54a282ffc5d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'voucher-name']</value>
      <webElementGuid>0c144886-7f47-4637-be89-b1ce38b5de2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'voucher-name' and @name = 'voucher_name' and @placeholder = 'e.g., New User Welcome Voucher']</value>
      <webElementGuid>e3636a99-1a8a-4b55-a092-37a3d90a4df0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
