<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Link my Farad Code to this voucher</name>
   <tag></tag>
   <elementGuidId>3cc21080-1133-44eb-bead-ea2d1fc8f8c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.voucher-checkbox-card__box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' voucher-checkbox-card__box ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>45582a71-20f7-4223-b616-d44b3206f5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>voucher-checkbox-card__box</value>
      <webElementGuid>d058a5f7-7f92-42ff-bcca-f9b325ca4383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>083ad5bc-2e95-4836-ab77-af2eac735f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-40849e004101fc2aa65fc1f8a9013716</value>
      <webElementGuid>62ffd8e4-2878-4522-bbc5-6091fd6fec4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' voucher-checkbox-card__box ')]</value>
      <webElementGuid>4789da12-ef38-40dd-92ea-9c0616faa149</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' voucher-checkbox-card__box ')]</value>
      <webElementGuid>137222fc-5ae4-4a91-8945-91bee43a62d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
