<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_https_www.example.com</name>
   <tag></tag>
   <elementGuidId>8dc5de41-5457-49db-9ec1-94b44d15a874</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'website_url']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#website_url</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c562e8c-fc0a-4a02-b8f1-03fef2e47300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prof-field__input</value>
      <webElementGuid>edaa8a5d-dabb-45e7-8fe2-dd492169a950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>8e02e3c8-cdc8-4c78-952c-d2c1ef217878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>website_url</value>
      <webElementGuid>588c6b89-f061-4b85-9921-0c2b86b1fdd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>website_url</value>
      <webElementGuid>68fc7d5b-ecbe-4226-872b-de15b064fece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>www.google.com</value>
      <webElementGuid>d4a829a9-04c3-4a78-b714-823f1b80b3f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>https://www.example.com</value>
      <webElementGuid>165012c9-242c-46f5-9b63-42dff63355e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>0feaaa61-8191-4ce6-9468-79ec079cc7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>ffd863ee-150f-4dfb-876a-374745fa167d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6de789677578611618e672c71fb3d5c1</value>
      <webElementGuid>aefc51f4-1338-4138-94c5-b56831794062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'website_url']</value>
      <webElementGuid>316f08b2-84fb-49e2-8231-c6d502a07b45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'website_url']</value>
      <webElementGuid>6cb364cf-66e6-4fdd-ae7e-05403cd7dc1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'url' and @id = 'website_url' and @name = 'website_url' and @placeholder = 'https://www.example.com']</value>
      <webElementGuid>ac2d4209-50ca-46e3-8d26-6d43477878a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
