<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search by name, email, or ID</name>
   <tag></tag>
   <elementGuidId>9f0861d8-a095-4924-950e-a1078c4a4fde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'send-to']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#send-to</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>959a1a15-f58d-424c-b1a7-5bb9e1699ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>send-fund-form__input</value>
      <webElementGuid>81abce41-ae18-4ce4-9be4-aeb27e1f583b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>1746f024-544f-4a43-8309-b45c8b1f63ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>send-to</value>
      <webElementGuid>58cbfe48-1a63-40db-9056-e57e7417438b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ddlUser</value>
      <webElementGuid>fedc5b5f-7b62-4e2f-af17-a2bb7b685a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by name, email, or ID</value>
      <webElementGuid>fac8e9d8-279c-43dd-94e5-5a13ba2671e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a1ac891d-3d3c-424f-bdd3-e5a83db6ab91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3cae9aa7-9f47-4d01-8674-2cbc627ddac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search recipient by name, email, or ID</value>
      <webElementGuid>7732d24b-db4a-4cc3-a78d-a257dc35ca03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7c09b52501e8a5e1c6d15c4484e9a81c</value>
      <webElementGuid>a79f93bc-12a2-4c2d-a4e9-6041fdf97629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'send-to']</value>
      <webElementGuid>1c5c43c6-8a08-4c8f-8647-aaf2e5df0756</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'send-to']</value>
      <webElementGuid>527f9863-cb90-4acf-a48d-a02d79a2ee92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'send-to' and @name = 'ddlUser' and @placeholder = 'Search by name, email, or ID']</value>
      <webElementGuid>1c9550c6-48b3-4b92-963e-ce5d88811b35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
