<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter amount to retire</name>
   <tag></tag>
   <elementGuidId>f0706147-cf0d-47da-bd15-0460ba21e452</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tl-retire-qty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'tl-retire-qty']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4052017-a168-4816-b16c-5e44115c98a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tl-smodal__input tl-smodal__input--icon tl-trade-numeric-input</value>
      <webElementGuid>29be5234-7402-4fde-8c51-9816c9ed18e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d11778ef-ddb2-470a-8ee3-f99089460a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tl-retire-qty</value>
      <webElementGuid>21981700-f5be-47c4-90dc-be05520fddd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>retire_qty</value>
      <webElementGuid>43eadbab-768c-4541-8da7-ff202c3c43ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>54c8c265-7681-4fe8-a531-a77bf10500c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>fd098d65-ce9d-4d6e-9039-303f4ee27998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>38f5615a-5251-4e04-930a-c1722fb6a740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>434f1d76-d92e-4f79-964f-18f9d2bb014e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-step</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>883c29c9-3856-4a1d-9f86-c719dce33e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>56938ba3-ff50-432c-bd19-a8347728b879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter amount to retire</value>
      <webElementGuid>394dbc85-db51-4a1d-994e-527cc3d76936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6c143937-4655-47dc-9930-dc486b66ef48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e613e010-fca7-42e5-a100-37d7d122b60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f56872294c482417f4b7c886860c4d48</value>
      <webElementGuid>28584f64-c12f-4eac-a35b-20da9371f32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'tl-retire-qty']</value>
      <webElementGuid>5a83ff6b-baa0-461b-9949-5f74e07b130e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'tl-retire-qty']</value>
      <webElementGuid>f3a197a2-fdf6-49cc-be7d-0ba555e0c4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tl-retire-qty' and @name = 'retire_qty' and @placeholder = 'Enter amount to retire']</value>
      <webElementGuid>4729721b-8bc6-40f4-b28a-94d92114b307</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
