<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tokenBuyQuantity</name>
   <tag></tag>
   <elementGuidId>cc2a8763-e760-4c78-b585-f0b2dd5ef434</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tl-buy-qty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'tl-buy-qty']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb84fe6c-dc7b-4b62-a9fb-458c9ef871fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tl-smodal__input tl-smodal__input--icon tl-trade-numeric-input</value>
      <webElementGuid>cd7bc6b1-dae9-4b04-a9b4-864f95000fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b67a2974-a65a-4582-b6ee-363bb5dc1f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tl-buy-qty</value>
      <webElementGuid>1bdf9331-697b-4ae1-992c-125cc8c36f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>buy_qty</value>
      <webElementGuid>ef92f180-d9ac-4f83-a669-050482b7cb35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>8dc1886d-ea2a-4cd6-988d-f2fc25e5da25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>623bf7f9-2cf2-4efd-b661-3d292dd81a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>7963f134-cfb2-42a6-9dc4-8dded593070e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>3b084ff0-b714-44c4-b127-154ffe00e8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-step</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>8acfa7df-063b-4a30-a7b1-a1a05e06fd15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>725bc87f-c47e-4cfb-8254-dbb7091cb201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter token amount</value>
      <webElementGuid>758652dd-783f-4070-8473-7114583c2246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>88af056d-eb42-412d-a870-c1d24970dbf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>66368dae-dab1-4095-8f49-42f935fd6754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f4e64e2fd4d11a7266b45e3aef1475ee</value>
      <webElementGuid>1f463c1f-2dbd-4d23-9c0f-dea7bb43921a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'tl-buy-qty']</value>
      <webElementGuid>ec9cee81-a1e4-4ccf-9c46-c930261e9199</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'tl-buy-qty']</value>
      <webElementGuid>909a49b3-7cd0-457d-adde-3a88ae25bfc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tl-buy-qty' and @name = 'buy_qty' and @placeholder = 'Enter token amount']</value>
      <webElementGuid>4a8bce2a-30de-437b-9a87-391c9f282fc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
