<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tokenSellQuantity</name>
   <tag></tag>
   <elementGuidId>d3cf79e8-92b3-4c03-86c1-36ca54a62d7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tl-sell-qty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'tl-sell-qty']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2929e2d9-2f63-4c6d-b102-263e921e639e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tl-smodal__input tl-smodal__input--icon tl-trade-numeric-input</value>
      <webElementGuid>753fcf2a-24e2-4118-874e-641738327d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>862df5c7-e609-4743-9e6e-28909bf4a3e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tl-sell-qty</value>
      <webElementGuid>9fa60952-d79d-4b2c-8a1d-aa695b0e4656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sell_qty</value>
      <webElementGuid>65188a7f-b0af-4723-8068-27bd3c8b9a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>b7167640-b87a-4353-a29b-2a2e776cf21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>0b2fb67c-2dcc-4bc0-afec-9a043800b4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>ed4c6135-0ceb-4803-ba1e-057a472b3f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>1e1acf06-4d9b-41d7-b5ee-02438ad6ec84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-step</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>7a1f2849-0e24-4d63-bf13-806bfcaec77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>6c59287b-ada0-4e68-8b04-cbc0dd3eb11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter token amount</value>
      <webElementGuid>bc45ac6c-437d-4ab8-ba74-c56ab9493daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>820d76b1-590c-4a7d-8d1d-12d3a4917646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8b7cbea7-558c-4c55-9368-967ddcb2206c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3af1a7ccb3f88a8584c0e562219de610</value>
      <webElementGuid>17f2bb54-de64-40c1-be0b-f51c793a2282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'tl-sell-qty']</value>
      <webElementGuid>b35d899b-92c1-46f9-bc70-f58365157fc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'tl-sell-qty']</value>
      <webElementGuid>de6da15e-2a26-4396-8404-ccbd525bd6b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tl-sell-qty' and @name = 'sell_qty' and @placeholder = 'Enter token amount']</value>
      <webElementGuid>6a42703f-0cd4-4b2f-8f3e-0fa7d00fb1bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
