<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tokenSellPrice</name>
   <tag></tag>
   <elementGuidId>31a67d49-d107-4a83-9cfe-c40bb5705060</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tl-sell-price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'tl-sell-price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfa794c8-c116-4465-997d-caad8751c251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tl-smodal__input tl-smodal__input--prefix tl-trade-numeric-input</value>
      <webElementGuid>2f29a0fd-a1c1-4f23-8950-bec91e30227d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>053abf1b-6b2c-4e9c-8332-b756035ce730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tl-sell-price</value>
      <webElementGuid>2d74e7cc-989c-4ad5-b5a3-43dd2f21336d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sell_price</value>
      <webElementGuid>881e0dc1-f11b-4c0a-ba42-4f5d45861e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>56d415f1-2c53-452c-9c50-5e145bebd52b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>a9eca7a5-1cee-4779-bdfd-eba65f269409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>bca973e5-b742-4156-812f-867d162ee3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>c3697b99-0b33-4e80-94fb-e947ba1fb03d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-step</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>849bd48b-3b68-4450-a272-cb1590c06d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>0f9120c2-f8b9-471a-a103-c2f28e73c906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>f9185bb3-b10e-4037-bd8a-5acc1992776a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>687048c8-5548-4b47-b457-252544283b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>34d8f5f1-ed2f-46ed-8ab7-27bb673c2009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8298870e1e4890ed7cd7246430aaf1b7</value>
      <webElementGuid>5626a53d-de64-4a7d-a31a-b9a19db8238c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'tl-sell-price']</value>
      <webElementGuid>d539783d-30ba-4591-90e7-3b250be4271c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'tl-sell-price']</value>
      <webElementGuid>b95c6340-1ba9-48b4-96df-f84085b0afa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tl-sell-price' and @name = 'sell_price' and @placeholder = '0.00']</value>
      <webElementGuid>05b42ca2-8c5e-427a-a075-861ba53d4c57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
